name:                prolog-engine
version:             0.1.0.0
github:              "Github nikelin/prolog-engine"
license:             BSD3
author:              "Cyril Karpenko <kyrylok2@illinois.edu>"
maintainer:          "Cyril Karpenko <self@nikelin.ru>"
copyright:           "2021 Cyril Karpenko <kyrylok2@illinois.edu>"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            App category here

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/nikelin/prolog-engine#readme>

dependencies:
- base >= 4.7 && < 5
- containers >= 0.6 && < 0.7
- unordered-containers >= 0.2
- megaparsec
- hspec
- hspec-contrib
- text

library:
  source-dirs: src

executables:
  prolog-engine-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - prolog-engine

tests:
  prolog-engine-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - prolog-engine
